# Generated by Django 5.2.15 on 2026-10-05 04:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueResearchDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('statement', models.TextField(blank=True, default='')),
                ('success_criteria', models.TextField(blank=True, default='')),
                ('conclusion_html', models.TextField(blank=True, default='<p></p>')),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verdict_at', models.DateTimeField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, default='', max_length=800)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('artifact_url', models.URLField(blank=True, default='', max_length=800)),
            ],
            options={
                'verbose_name': 'Issue Research Details',
                'verbose_name_plural': 'Issue Research Details',
                'db_table': 'issue_research_details',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ResearchGraphLayout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scope_type', models.CharField(choices=[('project', 'Project'), ('cycle', 'Cycle'), ('module', 'Module'), ('view', 'View')], max_length=20)),
                ('scope_id', models.UUIDField()),
                ('nodes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Research Graph Layout',
                'verbose_name_plural': 'Research Graph Layouts',
                'db_table': 'research_graph_layouts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='research_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed'), ('proposed', 'Proposed'), ('testing', 'Testing'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('inconclusive', 'Inconclusive'), ('superseded', 'Superseded'), ('valid', 'Valid'), ('invalidated', 'Invalidated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='research_type',
            field=models.CharField(blank=True, choices=[('question', 'Question'), ('hypothesis', 'Hypothesis'), ('experiment', 'Experiment'), ('evidence', 'Evidence')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='project',
            name='research_graph_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'research_type', 'research_status'], name='issue_research_type_status_idx'),
        ),
        migrations.AddField(
            model_name='issueresearchdetails',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='issueresearchdetails',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='db.issue'),
        ),
        migrations.AddField(
            model_name='issueresearchdetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='issueresearchdetails',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='issueresearchdetails',
            name='verdict_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_verdicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueresearchdetails',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='researchgraphlayout',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='researchgraphlayout',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='researchgraphlayout',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='researchgraphlayout',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='researchgraphlayout',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'scope_type', 'scope_id'), name='research_graph_layout_unique_scope_when_deleted_at_null'),
        ),
    ]
